### PR TITLE
Prevent installation of modules in wrong directory

### PR DESCRIPTION
**Pull request by MaximilianKresse**
At the moment it is possible that the composer modules was installed into the wrong directory. See #3 

With this fix it shouldn't be possible to install modules into the wrong modules directory and both ways to install simplesamlphp are still supported.

~~The drawback of this change is that all simplesamlphp modules have to require simplesamlphp to ensure the correct installation order by composer but I think this is the correct way because the modules just doesn't make sense without simplesaml.~~ This problem exists already. It isn't required but should be prevered.

### CODE REVIEW

**Comment by tvdijen** [comment]
I'm not thrilled of the circular dependency this would create...
It kills our unit tests: https://travis-ci.com/simplesamlphp/simplesamlphp-module-discopower/jobs/261556590#L236

**Comment by MaximilianKresse** [comment]
Mhh 🤔 But if I see this correctly the problem is already there even without this change. The discopower module requires the composer module which requires simplesaml which requires discopower "^0.9" but in CI environment the discopower module is in version "dev"... So it's only remotly related to this change. I would have two ideas to fix this problem for CI. 
**First:** Remove the module dependencies from the main simplesamlphp composer.json - I don't really understand why this wasn't done in the first place with 1.18 - but this is a BC and so probably not the best way at the moment. 
**Second:** Change the composer.json as part of the CI and add something like this: 
```
    "replace": {
        "simplesamlphp/simplesamlphp-module-discopower": "*"
    },
```
It's not really "the nice way" but it should work 😬

**Comment by MaximilianKresse** [comment]
With the lastest change it is now possible to install custom simplesamlphp modules from private composer repositories (like described in #3 - we also have an equal environment). The problem with my first change was that it just triggered an error because composer first checks which packages are already installed. If the composer module cannot find simplesamlphp in ```ModuleInstaller::isInstalled()``` the method will return **false** instead of throwing an exception, because we can be sure that no simplesamlphp module is installed if simplesamlphp isn't installed.

**Comment by jaimeperez** [comment]
Maybe I am missing something, but it has always been possible to install custom SimpleSAMLphp modules from private repos. We have been doing so for years now...

**Comment by MaximilianKresse** [comment]
Yeah we too :-) 

Ok here the full problem description:

Our project composer json:
```json
{
    "name": "our project",
    "description": "",
    "type": "project",
    "minimum-stability": "stable",
    "license": "proprietary",

    "require": {
        "php": ">=7.3.0",
        "simplesamlphp/simplesamlphp": "^1.18",
        "our-vendor/simplesamlphp-module-our-theme": "^1.0",
        "simplesamlphp/composer-module-installer": "^1.1"
    },

    "repositories": [
        {
            "type": "composer",
            "url": "URL TO SATIS"
        }
    ]
}
```

Here the composer.json of our custom theme:
```json
{
    "name": "our-vendor/simplesamlphp-module-our-theme",
    "type": "simplesamlphp-module",
    "minimum-stability": "stable",
    "license": "proprietary",

    "require": {
        "php": ">=7.1",
        "simplesamlphp/composer-module-installer": "^1.1.5",
        "simplesamlphp/simplesamlphp": "^1.17"
    }
}
```

When we use ```composer install``` on a new project we get the problem that all default simplesaml modules are installed into the "modules" directory of the main directory:
image

Content:
image

Note: Our module theme is inside the correct directory:
image

The main problem can be found in the ModuleInstaller class:
https://github.com/simplesamlphp/composer-module-installer/blob/master/src/SimpleSamlPhp/Composer/ModuleInstaller.php#L30

If a package cannot be found it will use "." as $ssp_path which is there because it also should be possible to install simplesaml modules when we clone the main repository and install a module there. Because of this I added the more explicit behaviour: https://github.com/MaximilianKresse/composer-module-installer/blob/patch-2/src/SimpleSamlPhp/Composer/ModuleInstaller.php#L39

And completly prevented that a package is installed inside the root modules directory if the root repository isn't "simplesamlphp/simplesamlphp" (so if the project isn't a git clone of https://github.com/simplesamlphp/simplesamlphp)

And the last change was to enable custom modules again which I prevented in some cases with my previous changes:
https://github.com/MaximilianKresse/composer-module-installer/blob/patch-2/src/SimpleSamlPhp/Composer/ModuleInstaller.php#L20

**Comment by jaimeperez** [comment]
Ok, so first of all, your composer should not require `simplesamlphp/composer-module-installer`. That's a dependency for modules, but you don't need it yourself.

Second, if I follow correctly, the problem here is that composer tries to install a module but it can't find SimpleSAMLphp installed, and then it proceeds with the current directory, given how the code is structured. Did I get that right?

If that's the case, something weird is going on. A module should never be installed if SimpleSAMLphp is not installed, and if it's installed, composer should not fail to find its directory. This is why composer performs dependency resolution. You ask for SimpleSAMLphp and your custom module, and your custom module asks for SimpleSAMLphp as well. Composer should resolve this into: "_install SimpleSAMLphp first, then the composer-module-installer (which also depends on SSP), and finally your module_". At that point, SSP is available and the module installer should be able to find the installation directory of SSP.

So my take on this is that your fix is just addressing the symptom, rather than the actual error. The problem here is not that the module gets installed in the root when SSP is not yet installed. The problem is that such situation should never happen, yet it does for some reason. We need to figure out what that reason is.

**Comment by tvdijen** [comment]
Also the theme shouldn't require SSP.. So there's two obsolete require-statements

**Comment by MaximilianKresse** [comment]
> Ok, so first of all, your composer should not require `simplesamlphp/composer-module-installer`. That's a dependency for modules, but you don't need it yourself.

Ok. But it doesn't change the behaviour.


> Second, if I follow correctly, the problem here is that composer tries to install a module but it can't find SimpleSAMLphp installed, and then it proceeds with the current directory, given how the code is structured. Did I get that right?

Yes.

> If that's the case, something weird is going on. A module should never be installed if SimpleSAMLphp is not installed, and if it's installed, composer should not fail to find its directory. This is why composer performs dependency resolution. You ask for SimpleSAMLphp and your custom module, and your custom module asks for SimpleSAMLphp as well. Composer should resolve this into: "_install SimpleSAMLphp first, then the composer-module-installer (which also depends on SSP), and finally your module_". At that point, SSP is available and the module installer should be able to find the installation directory of SSP.
>
> So my take on this is that your fix is just addressing the symptom, rather than the actual error. The problem here is not that the module gets installed in the root when SSP is not yet installed. The problem is that such situation should never happen, yet it does for some reason. We need to figure out what that reason is.

Yes. Correct I'm just fighting the symptoms. But strangely everything works like expected with my changes. I'll look a little bit further into composer and try to find out why everything is happening like it does.

> Also the theme shouldn't require SSP.. So there's two obsolete require-statements

Why not? My theme doesn't do anything without SSP and within the templates there are probably some dependencies to the actual version of SSP and not every version of my theme will work with every version of SSP. In my eyes **it is** clearly a dependency.

**Comment by MaximilianKresse** [comment]
I created a very small example to reproduce the error:
```json
{
    "require": {
        "simplesamlphp/simplesamlphp": "^1.18",
        "maximilian-kresse/simplesamlphp-module-installerdummytest": "^1.0"
    }
}
```
My dummy module can be  found here: https://github.com/MaximilianKresse/simplesamlphp-module-installerdummytest

Just call ```composer install``` and the module installer will create a modules directory. 

The composer install log:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 63 installs, 0 updates, 0 removals
  - Installing simplesamlphp/composer-module-installer (v1.1.6): Loading from cache
  - Installing whitehat101/apr1-md5 (v1.0.0): Loading from cache
  - Installing symfony/polyfill-ctype (v1.13.1): Loading from cache
  - Installing webmozart/assert (1.6.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.13.1): Loading from cache
  - Installing twig/twig (v2.12.2): Loading from cache
  - Installing symfony/yaml (v4.4.1): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/service-contracts (v2.0.1): Loading from cache
  - Installing symfony/dependency-injection (v4.4.1): Loading from cache
  - Installing psr/log (1.1.2): Loading from cache
  - Installing symfony/polyfill-php73 (v1.13.1): Loading from cache
  - Installing symfony/polyfill-php72 (v1.13.1): Loading from cache
  - Installing symfony/polyfill-intl-idn (v1.13.1): Loading from cache
  - Installing symfony/mime (v5.0.1): Loading from cache
  - Installing symfony/http-foundation (v4.4.1): Loading from cache
  - Installing symfony/event-dispatcher-contracts (v1.1.7): Loading from cache
  - Installing symfony/event-dispatcher (v4.4.1): Loading from cache
  - Installing symfony/var-dumper (v5.0.1): Loading from cache
  - Installing symfony/debug (v4.4.1): Loading from cache
  - Installing symfony/error-handler (v4.4.1): Loading from cache
  - Installing symfony/http-kernel (v4.4.1): Loading from cache
  - Installing symfony/filesystem (v5.0.1): Loading from cache
  - Installing symfony/config (v4.4.1): Loading from cache
  - Installing symfony/routing (v4.4.1): Loading from cache
  - Installing twig/extensions (v1.5.4): Loading from cache
  - Installing simplesamlphp/twig-configurable-i18n (v2.2): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-sqlauth (v0.9.1): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-statistics (v0.9.4): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-sanitycheck (v0.9.0): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-smartattributes (v0.9.1): Loading from cache
  - Installing phpfastcache/riak-client (3.4.3): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-riak (v0.9.1): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-radius (v0.9.3): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-preprodwarning (v0.9.1): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-oauth (v0.9.1): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-ldap (v0.9.4): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-negotiate (v0.9.4): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-metarefresh (v0.9.3): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-memcachemonitor (v0.9.1): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-memcookie (v1.2.2): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-expirycheck (v0.9.1): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-exampleattributeserver (v1.0.0): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-discopower (v0.9.1): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-consent (v0.9.4): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-consentadmin (v0.9.1): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-cdc (v0.9.1): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-cas (v0.9.1): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-authyubikey (v0.9.1): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-authx509 (v0.9.1): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-authwindowslive (v0.9.1): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-authtwitter (v0.9.1): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-authorize (v0.9.0): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-authfacebook (v0.9.2): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-authcrypt (v0.9.1): Loading from cache
  - Installing simplesamlphp/simplesamlphp-module-adfs (v0.9.5): Loading from cache
  - Installing robrichards/xmlseclibs (3.0.4): Loading from cache
  - Installing simplesamlphp/saml2 (v4.1.2): Loading from cache
  - Installing phpmailer/phpmailer (v6.1.3): Loading from cache
  - Installing gettext/languages (2.6.0): Loading from cache
  - Installing gettext/gettext (v4.8.2): Loading from cache
  - Installing simplesamlphp/simplesamlphp (v1.18.2): Loading from cache
  - Installing maximilian-kresse/simplesamlphp-module-installerdummytest (v1.0.1): Loading from cache
symfony/yaml suggests installing symfony/console (For validating YAML files using the lint command)
symfony/dependency-injection suggests installing symfony/finder (For using double-star glob patterns or when GLOB_BRACE portability is required)
symfony/dependency-injection suggests installing symfony/expression-language (For using expressions in service container configuration)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
symfony/event-dispatcher-contracts suggests installing psr/event-dispatcher
symfony/var-dumper suggests installing symfony/console (To use the ServerDumpCommand and/or the bin/var-dump-server script)
symfony/http-kernel suggests installing symfony/browser-kit
symfony/http-kernel suggests installing symfony/console
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
twig/extensions suggests installing symfony/translation (Allow the time_diff output to be translated)
simplesamlphp/simplesamlphp-module-negotiate suggests installing ext-krb5 (Needed in case the SimpleSAMLphp negotiate module is used)
phpmailer/phpmailer suggests installing league/oauth2-google (Needed for Google XOAUTH2 authentication)
phpmailer/phpmailer suggests installing hayageek/oauth2-yahoo (Needed for Yahoo XOAUTH2 authentication)
phpmailer/phpmailer suggests installing stevenmaguire/oauth2-microsoft (Needed for Microsoft XOAUTH2 authentication)
gettext/gettext suggests installing illuminate/view (Is necessary if you want to use the Blade extractor)
simplesamlphp/simplesamlphp suggests installing predis/predis (Needed if a Redis server is used to store session information)
simplesamlphp/simplesamlphp suggests installing ext-radius (Needed if a Radius backend is used)
simplesamlphp/simplesamlphp suggests installing ext-memcache (Needed if a Memcache server is used to store session information)
simplesamlphp/simplesamlphp suggests installing ext-mysql (Needed if a MySQL backend is used, either for authentication or to store session information)
Writing lock file
Generating autoload files
```

What strikes me is that the simplesamlphp/composer-module-installer is installed first even before SSP and SSP is installed as second last after all simplesaml modules (except of my dummy module). 

My explanation to this behaviour would be: At the moment you already have a circular dependency - SSP requires the modules, every modules requires the module installer and the module installer requires SSP. So composer is probably in some kind of automatic conflict resolution to solve this circular dependency. In my opinion every SSP module **MUST** depend on SSP directly because it uses code of SSP and/or depend on specific directory structur. SSP is clearly a dependency of SSP modules and should be handled like one. 

So my pull request is probably not necessary but I think the code should be hardened to prevent such unexpected results.

**Comment by MaximilianKresse** [comment]
I moved the question whether a module should require SSP to an own issue.

So this PR ist just here to harden the code and prevent unforeseen consequences.

**Comment by MaximilianKresse** [comment]
ping?

**Comment by MaximilianKresse** [comment]
What should happen with this? If you don't want this PR lets close this but the problem still exists and it should **never** be possible of a composer module to install something into the wrong directory.

**Comment by jaimeperez** [comment]
Hi @MaximilianKresse!

Sorry for the long time it took to respond. I just checked and verified the behaviour. I also verified that removing SimpleSAMLphp itself as a dependency gets rid of the problem, and then that gets installed first, and all modules land correctly in the `modules` directory.

Considering we have work in progress that would allow us to stop needing modules to be in a given directory, and that would allow us as well to get rid of this repo itself, I'm in doubt on whether we should merge this or not. There is also a way to avoid the issue, although I reckon it's counter-intuitive and feels wrong in my head.

Have you checked that everything keeps working fine with your patch for all other use cases?

**Pull request closed without merging**
